# Generated by Django 6.0.6 on 2026-06-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('XL', 'Extra Large')], default=2, max_length=2),
            preserve_default=False,
        ),
    ]
