# Generated by Django 6.0.6 on 2026-06-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='test@example.com', max_length=254)),
                ('phone', models.CharField(default='null', max_length=20)),
                ('shipping_address', models.TextField(default='null')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('tracking_link', models.URLField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_number', models.CharField(blank=True, max_length=255, null=True)),
                ('shipment_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
