<<<<<<< HEAD
# Generated by Django 6.0.6 on 2026-06-25 10:15
=======
# Generated by Django 6.0.6 on 2026-06-25 11:41
>>>>>>> e3cda03202b4a45e9bc64c8d318c7a4c8135073d

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_product_image'),
        ('adminapp', '0008_orderitem'),
    ]

    operations = [
    ]
