# Generated by Django 6.0.6 on 2026-06-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_product_image'),
        ('adminapp', '0008_orderitem'),
    ]

    operations = [
    ]
