# Generated by Django 6.0.6 on 2026-06-29 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sections',
            field=models.CharField(choices=[('none', 'None'), ('curated_edits', 'Curated Edits'), ('summer_blooms', 'Summer Blooms'), ('heritage_blooms', 'Heritage Blooms')], default='none', max_length=30),
        ),
    ]
