# Generated by Django 6.0.6 on 2026-06-30 05:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_product_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='sections',
            field=models.CharField(choices=[('none', 'None'), ('curated_redvelvet', 'Curated - Red Velvet'), ('curated_Chanderisilks', 'Curated - Chanderi Silks'), ('summer_chronicles', 'Summer Chronicles'), ('heritage_blooms', 'Heritage Blooms')], default='none', max_length=30),
        ),
    ]
