# Generated by Django 6.0.6 on 2026-07-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='material',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
