# Generated by Django 6.0.6 on 2026-07-08 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_alter_orderitem_material_alter_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
